---
- name: Cau hinh SW
  hosts: all
  gather_facts: no
  tasks:
    - name: show ip
      ios_command:
        commands: 'sh ip int br'
        register: output
    - debug: var=output.stdout_lines
