---
- name: Cau hinh switch
  hosts: all
  gather_facts: no

  tasks:
    - name: Create Loopback
      ios_interface:
        name: Loopback99
        state: up


    - name: show ip
      ios_command:
        commands:
          - sh ip int bri
      register: output
    - debug: var=output.stdout_lines
